services:
  - type: web
    name: nlh-tennis-club
    env: python
    branch: bs
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn my_tennis_club.wsgi:application --bind 0.0.0.0:$PORT
    pythonVersion: 3.11.15
