# Generated by Django 4.2.2 on 2023-12-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtname', models.CharField(max_length=100)),
                ('courttype', models.CharField(choices=[('G', '草地'), ('H', '硬地'), ('N', '泥地'), ('D', '地毯')], max_length=1)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
