# Generated by Django 4.2.2 on 2023-12-21 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 21)),
        ),
    ]
