# Generated by Django 4.2.2 on 2023-12-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_booking_reason_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='court_photos/'),
        ),
    ]
