# Generated by Django 3.2.18 on 2026-05-26 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_court_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2026, 5, 26)),
        ),
    ]
