# Generated by Django 4.2.2 on 2023-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230301_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
