# Generated by Django 4.2.2 on 2024-05-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
