# Generated by Django 4.2.2 on 2024-05-07 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=datetime.date, help_text='the day he pay fee', null=True, verbose_name='入會日期'),
        ),
    ]
