# Generated by Django 4.2.2 on 2024-05-07 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=datetime.date(2024, 5, 7), help_text='the day he pay fee', null=True, verbose_name='入會日期'),
        ),
    ]
