# Generated by Django 3.2.18 on 2026-05-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_initial_data'),
        ('members', '0009_alter_member_user'),
    ]

    operations = [
    ]
